### ISSUE TITLE
Qobuz playlists search

### ISSUE THREAD

**Issue by vvv-ibm** [medoc92/upmpdcli#111]
Hi,

I'm using BubbleUPnP as a control point and it looks like search results do not return Qobuz playlists?
Also, when listing playlists I only get 100 back when there are many more and since I cannot search by playlist name I can't get any of the older playlists.
Is this something you can fix or is it an issue with BubblUPnP?

Thanks!

**Comment by medoc92** [comment]
Hi,

The problem is that Bubble is quite specific when it starts a search, it requests either object.container.person.musicArtist or object.container.album.musicAlbum (apart from tracks). 

This results in the corresponding object lookups on Qobuz. Playlists are a separate search. I'm not too sure why Bubble does it this way, it could also just search for anything matching the criteria and sort whatever comes back. Actually Kazoo does exactly the same thing.

Both CPs could either be less specific or actually search for object.container.playlistContainer but they don't.

I'm not too sure what to do about this. Maybe I could conflate album and playlist searches.

The truth is that there is a mismatch between UPnP and the streaming services capabilities and that one is probably better off using the native (web or app) interface to build a favourites set, and use it when playing through upnp.

**Comment by vvv-ibm** [comment]
I'll be fine with including playlists results in album searches. 
However, I just figured out how to add playlists to my favorites so not a big deal if you don't. I have been using the apps to search and add to favorites anyway, just didn't realize that I could do it for playlists.
Thanks!
