### ISSUE TITLE
Onvolumechange doesn't work

### ISSUE THREAD

**Issue by farinjini** [medoc92/upmpdcli#26]
I wrote a small program in C++ to change my audio volume. It is called like so 
./AlsaVolume 50
 for example. However onvolumechange doesn't call this program as expected.

Kind regards, I'm really enjoying using your program.

**Comment by joerg-krause** [comment]
Did you set the full absolute path, e.g. '/home/*yourname*/AlsaVolume', to ```onvolumechange```?

**Comment by farinjini** [comment]
Yes I did

onvolumechange = /home/pi/documents/vGDB/AlsaVolume/AlsaVolume

**Comment by farinjini** [comment]
Some further info:
I set the log level to 4 and captured the log messages when I try changing the volume on the control point.

`libupnpp/device/device.cxx:292::UPNP_CONTROL_ACTION_REQUEST: SetVolume. Params: <?xml version="1.0"?>
<m:SetVolume xmlns:m="urn:schemas-upnp-org:service:RenderingControl:1">
<InstanceID xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="ui4">0</InstanceID>
<Channel xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="string">Master</Channel>
<DesiredVolume xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="ui2">17</DesiredVolume>
</m:SetVolume>

src/renderctl.cxx:189::UpMpdRenderCtl::setVolume: volume 17 delta 33
src/mpdcli.cxx:342::MPDCli::setVolume: vol 17 isMute 0
src/mpdcli.cxx:103::mpd_run_set_volume(M_CONN, volume) failed: problems setting volume
src/mpdcli.cxx:106::mpd_run_set_volume(M_CONN, volume) server error: 52
libupnpp/device/device.cxx:292::UPNP_CONTROL_ACTION_REQUEST: GetPositionInfo. Params: <?xml version="1.0"?>
<m:GetPositionInfo xmlns:m="urn:schemas-upnp-org:service:AVTransport:1">
<InstanceID xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="ui4">0</InstanceID>
</m:GetPositionInfo>`

**Comment by farinjini** [comment]
Some further info,

I set log level to 4 and captured the log messages when I change the volume on my control point.

[log.txt](https://github.com/medoc92/upmpdcli/files/118123/log.txt)

**Comment by joerg-krause** [comment]
> src/mpdcli.cxx:103::mpd_run_set_volume(M_CONN, volume) failed: problems setting volume
src/mpdcli.cxx:106::mpd_run_set_volume(M_CONN, volume) server error: 52

Looks like a MPD error.

**Comment by farinjini** [comment]
From my understanding (reading the docs), upmpdcli should not be trying to set the volume on mpd (if that's where the problem is from), it should just invoke the app specified with the new volume level as the 1st parameter.

**Comment by joerg-krause** [comment]
Maybe it's related to this issue: https://github.com/medoc92/upmpdcli/issues/1

**Comment by medoc92** [comment]
From a quick look at the code, this is not what happens. If setting the volume fails, the onvolume command is not called.

If

**Comment by farinjini** [comment]
OK, I'll look at the source and make modifications that work for me. Thanks and great work. Closing this now.

**Comment by medoc92** [comment]
Reopening, because there is a valid case for having a more adaptable approach for onvolumechange, another user would like to use this to actually perform the volume change (with a script, and because mpd apparently can't do it for some reason).

Joerg, if you are around, what was your original purpose for this hook ?

**Comment by joerg-krause** [comment]
I use it on an embedded system for storing the new volume immediately to the UBI flash filesystem as both alsactl and the UBI system write to flash with some seconds delay. So, in case of a power-cut the new volume setting will be lost otherwise.

Another use case is to trigger the new volume to a LCD display attached to the device.

A common issue is that upmpdcli does not run as root, so if some actions requires root priviliges sudo has to be used for calling the script and the user upmpdcli has to be member of the sudo group.

**Comment by medoc92** [comment]
The following commit should allow replacing controlling the volume through mpd with an external script:

https://github.com/medoc92/upmpdcli/commit/b87516ae07e719941c25f72b2ccf234903fd2839

Set externalvolumecontrol in the config, and possibly define getexternalvolume as a script to retrieve the volume value. If externalvolumecontrol is set, onvolumechange is executed instead of calling mpd, and is supposed to perform the volume change.
