### ISSUE TITLE
qobuz service login not working 1.2.10 Raspian Jessy

### ISSUE THREAD

**Issue by volkma** [medoc92/upmpdcli#65]
Hi,
after updating to 1.2.10 it seems that the qobuz login in no longer working.
I use BubbleUpnP as control point. When i try to brwose qobuz at the mediaserver there is the error message "Service login or communication failure".
Any suggestions?
Regards
Volkmar

**Comment by medoc92** [comment]
This is strange, because 1.2.10 was quite specifically tested with qobuz (the supposed search improvements are qobuz-related). 

To investigate, we need to look at the messages from upmpdcli and those from the python subprocess.

Edit upmpdcli.conf, set the log level to 4, and no log file name (log to stderr).

If you are running with systemd, use:
   journalctl -f -u upmpdcli
in a terminal (this will show the live messages from the program and its subprocesses),

If you are not on a system using systemctl, stop the normal instance, then start upmpdcli as:
    sudo upmpdcli -c /etc/upmpdcli.conf

In both cases, when you have run the failing operation, ^C in the terminal, then copy-paste, and attach the log here. I am reasonably certain that the log does not include your password or login, but still, maybe grep for them...

**Comment by volkma** [comment]
Hi. Thanks for your quick reply. It seems that something messed up my installation. After i have installed everything from scratch the problem was gone.  The new search works great!! I really love this Qobuz integration.

**Comment by medoc92** [comment]
Great ! That's good news. Qobuz is nice, I had temporary subscriptions to Tidal, gmusic and Qobuz while working on this, and I kept Qobuz.
