### ISSUE TITLE
seeking problem

### ISSUE THREAD

**Issue by estshorter** [medoc92/upmpdcli#67]
Openhome controller cannot seek audio files.
Maybe a problem in the following url relates to this issue.
http://forums.linn.co.uk/bb/showthread.php?tid=30795

software environment:
* kazoo server as a server on windows10
* kazoo or upplay as a controller on windows10
* upmpdcli v1.2.10 as a renderer on a raspberry pi (os: moode audio) with disabled checkcontentformat

P.S.
I confirmed that Kazoo can seek by using BubbleUPnP as a renderer on a android device.

**Comment by medoc92** [comment]
Hi,

I am seeing something similar, using minimserver:

- If I add the track from Kazoo, it can't be seeked either from upplay or Kazoo. Kazoo displays a duration, but upplay does not. Bubble Upnp displays a duration and can seek (this is a smart piece of software!)
- If I add the track from upplay, it can be seeked from upplay and Bubble but not from Kazoo. 
- Kazoo does display the duration information in both cases, so I have no idea why it does not allow seeking.


I guess that the thread you link to is relevant, but one of the Linn guys seems to say that the issue should only occur when the track is added from an UPnP Media Server, not from Kazoo server (so it would not explain your case).

So it's not too clear where the bug comes from. I am going to look into why upplay does not display the duration or allow seeking when the track is from kazoo, and maybe this will provide an explanation.

**Comment by estshorter** [comment]
Thank you for your quick reply.
I'm going to use minimserer instead.

**Comment by medoc92** [comment]
I fixed upplay to retrieve the duration from  OHTime when it is not set in the metadata (when the track was added from Kazoo), so it now works like bubble UPnP (git source only for now).

Kazoo still won't seek, and I have no idea why. There is probably something it does not like in the upmpdcli interface, but I have no idea what. I think that it would be best to ask them... Closing this for now, as I can't do anything more.
