### ISSUE TITLE
Reporting 'Sender' in 'Product' service 'Source' state variable when bearing the 'Sender' service

### ISSUE THREAD

**Issue by joerg-krause** [medoc92/upmpdcli#84]
The OpenHome [SenderService](http://wiki.openhome.org/wiki/Developer:SenderService) developer page states: "If a device's Product service reports an attribute source of type 'Sender', then that device is guaranteed to bear the Sender service."

When running the mpd2sc as the Sender (and sc2mpd as the Receiver), the Product service 'Source' attribute does not report a 'Sender' value, but: "Info Time Volume Receiver".

Note, that the device reports the "urn:av-openhome-org:serviceId:Sender" service, so the Sender is running for sure. Tested with the GUPnP tool on Linux.

**Comment by joerg-krause** [comment]
I also noticed, that the Sender is listed as a separate UPnP device in the UPnP network. The device type listed when starting upmpdcli is _"urn:schemas-upnp-org:device:MediaRenderer:1"_ including, among others, the Receiver service _"urn:av-openhome-org:service:Receiver:1"_. When starting mpd2sc an additional device type _"urn:av-openhome-device:Sender:1"_ is created, having only _"urn:av-openhome-org:service:Sender:1"_ as a service. Is this correct?

**Comment by medoc92** [comment]
Yes, I think it's correct that the Sender is a different device and that upmpdcli does not report a Sender, because the Sender service is actually implemented by the separate mpd2sc process. The slightly strange thing is that this device does not have other openhome services like Product, but after all, this is a barely modified Linn sample program, so I guess that this should not be an issue, even if Product is supposedly mandatory (if I remember well).

Actually, it's exactly the same for the Windows and Mac Songcast apps: they just report a Sender service and nothing else.

**Comment by joerg-krause** [comment]
I figured it out that mpd2sc is derived from the ohSongcast sample program, so I asked the same question on the ohSongcast issue tracker: https://github.com/openhome/ohSongcast/issues/5.

Did you had a look at the Songcast implementation in ohPipeline already?

**Comment by medoc92** [comment]
Nope,  I always get a headache after looking at Linn code, so I limit my exposition :)

**Comment by joerg-krause** [comment]
I agree!

So, knowing why there are two UPnP devices, and knowing about a possible solution howto get the Sender service into the MediaRenderer device, I'll close this for now.
