### ISSUE TITLE
mp4 audio not playing

### ISSUE THREAD

**Issue by Sufi-Al-Hussaini** [medoc92/upmpdcli#85]
Audio for mp4 videos doesn't play, instead I get noise coming out of my speakers.
I saw related issue #53 and tried setting `checkcontentformat = 0`, but it still doesn't work. 

Also, I'm using the latest upmpdcli, so `http-get:*:video/mp4:*,` is already present in `/usr/share/upmpdcli/protocolinfo.txt`.

It is worth mentioning that I'm able to play mp4 files on my system using `vlc --vout none video.mp4`.

```
$ upmpdcli -v
Upmpdcli 1.2.12 libupnpp 0.15.1
```

Logs: 
```
$ /usr/bin/upmpdcli -c /etc/upmpdcli.conf
:3:libupnpp/control/cdircontent.cxx:108::checkobjok: found object of unknown class: [object.item.videoItem]
:2:src/upmpd.cxx:138::checkContentFormat: format check disabled
```
```
$ /usr/bin/mpd --no-daemon --stderr
client: [1] opened from 127.0.0.1:42639
player: played "http://192.168.1.229:34572/yt/stream?f=37&id=RhsDMeGFc6A&t=2"
```

**Comment by medoc92** [comment]
Hi,

Do you mean that this is an actual video file and that you want to play the audio stream ?

Actually, I tried, and this worked (with my sample), to my great surprise (video/mp4 is in protocolinfo because audio files are sometimes mistaken as video/mp4, not because I actually expected files with video).

This can't be an upmdcli issue actually, if it accepts to send the file to MPD (which it does because of checkcontentformat = 0 or because of video/mp4 being in the protocolinfo file), it's then up to MPD to do something with it.

So this is probably a problem of compatibility between the actual audio format in your file, and the MPD plugin which handles it, which is very probably ffmpeg.

One thing to try would be to copy the file to the mpd music directory and play it directly from an mpd client. If it does not work, you should report the issue to the MPD people (but first check the bug tracker to see if this might have been fixed in a recent version).

If local playing works, it means that the problem is restricted to the case when the data arrives through HTTP (instead of direct file access). This kind of issue is relatively common, and there have been many fixes in this area in recent mpd versions. You don't say what platform / version you are using, but the first thing to try would be to use the last mpd version (I can probably help if you give me the details).

**Comment by Sufi-Al-Hussaini** [comment]
Thank you for your insightful comments.

I just tried streaming video from BubbleUPnP and it worked. Turned out to be a problem with ArkMC iOS App (specifically with video streaming from youtube).

Thanks again for your help.
